import json
from collections.abc import Sequence
from pathlib import Path

import pytest
from render_fixtures import kitchen_sink, write_layout, write_template
from render_helpers import render_issues, report_of

from scireport import Bundle, Report
from scireport.errors import Issue, RenderError, TemplateError
from scireport.render import render_bundle
from scireport.render.pipeline import MANIFEST_NAME, check_bundle


def codes(issues: Sequence[Issue]) -> list[str]:
  return [i.code for i in issues]


def test_every_format_is_written_into_its_own_folder() -> None:
  result = render_bundle(kitchen_sink())
  assert result.formats == ('md', 'html', 'tex')
  assert sorted(result.files) == [
    'html/report.html',
    'md/attachments/all_rows.csv',
    'md/data.md',
    'md/figures/figures.curve.png',
    'md/images/figures.logo.png',
    'md/index.md',
    'render-manifest.json',
    'tex/attachments/all_rows.csv',
    'tex/figures/figures.curve.pdf',
    'tex/images/figures.logo.png',
    'tex/latexmkrc',
    'tex/report.tex',
    'tex/scireport-minimal.sty',
  ]
  assert result.issues == ()


def test_two_renders_are_byte_identical() -> None:
  first = render_bundle(kitchen_sink())
  second = render_bundle(kitchen_sink())
  assert first.files == second.files
  assert list(first.files) == sorted(first.files)


def test_output_has_no_clock_and_no_absolute_paths() -> None:
  result = render_bundle(kitchen_sink())
  for name, data in result.files.items():
    if not name.endswith(('.md', '.html', '.tex', '.sty', '.json', 'latexmkrc', '.csv')):
      continue
    text = data.decode('utf-8')
    assert '/home/' not in text and '/tmp/' not in text, name
    assert '\r' not in text, name


def test_the_render_manifest_records_inputs_versions_and_outputs() -> None:
  result = render_bundle(kitchen_sink())
  manifest = json.loads(result.files[MANIFEST_NAME])
  assert manifest == result.manifest
  assert manifest['spec'] == '1.0'
  assert manifest['template']['ref'] == 'generic@1' and len(manifest['template']['sha256']) == 64
  assert manifest['layout']['ref'] == 'minimal@1'
  assert manifest['formats'] == ['md', 'html', 'tex']
  assert manifest['engines']['markup'] == 'mistletoe'
  assert manifest['engines']['latex'] == 'lualatex'
  assert manifest['options']['toc'] is True
  assert set(manifest['input']['assets']) >= {'assets/figures/figures.curve.png'}
  assert manifest['outputs']['md/index.md']['bytes'] == len(result.files['md/index.md'])
  assert MANIFEST_NAME not in manifest['outputs']
  assert manifest['warnings'] == []


def test_the_manifest_changes_when_the_content_changes() -> None:
  one = render_bundle(kitchen_sink()).manifest['input']['manifest_sha256']
  two = render_bundle(kitchen_sink(outline=False)).manifest['input']['manifest_sha256']
  assert one != two


def test_markdown_splits_when_a_chapter_names_a_file() -> None:
  split = render_bundle(kitchen_sink(), formats=['md'])
  assert 'md/data.md' in split.files and 'md/index.md' in split.files
  single = render_bundle(kitchen_sink(), formats=['md'], md_split=False)
  assert 'md/data.md' not in single.files and 'md/report.md' in single.files
  text = single.files['md/report.md'].decode()
  assert '\n## Data\n' in text and '\n## Facts\n' in text
  index = split.files['md/index.md'].decode()
  assert '[2 Data](data.md#data)' in index
  assert split.files['md/data.md'].decode().startswith('<!-- Generated by scireport')
  assert '\n# Data\n' in split.files['md/data.md'].decode()


def test_forcing_a_split_without_files_still_writes_an_index() -> None:
  result = render_bundle(kitchen_sink(split=False), formats=['md'], md_split=True)
  assert 'md/index.md' in result.files and 'md/data.md' not in result.files


def test_flat_output_needs_one_format() -> None:
  result = render_bundle(kitchen_sink(), formats=['html'], flat=True)
  assert sorted(result.files) == ['render-manifest.json', 'report.html']
  with pytest.raises(TemplateError) as caught:
    render_bundle(kitchen_sink(), flat=True)
  assert caught.value.code == 'E801'


def test_the_bundle_picks_the_formats_and_unknown_ones_are_skipped() -> None:
  report = Report('T').add_text('t', 'x').set_render(formats=['md', 'docx'])
  assert render_bundle(report.build()).formats == ('md',)


def test_without_a_template_the_values_are_grouped_by_key() -> None:
  report = Report('T').add_number('b.x', 1).add_number('b.y', 2).add_number('a', 3)
  report.set_render(layout='minimal')
  text = render_bundle(report.build(), formats=['md'], flat=True).files['report.md'].decode()
  assert text.index('**A:**') < text.index('## B') < text.index('**X:**') < text.index('**Y:**')


def test_options_reach_the_layout() -> None:
  html = (
    render_bundle(
      kitchen_sink(), formats=['html'], options={'toc': 'false', 'accent': '#ff0000'}, flat=True
    )
    .files['report.html']
    .decode()
  )
  assert 'class="toc"' not in html.split('</style>')[1]
  assert '--accent: #ff0000' in html
  tex = render_bundle(kitchen_sink(), formats=['tex'], options={'paper': 'letter'}, flat=True)
  assert 'letterpaper' in tex.files['report.tex'].decode()


def test_bundle_options_are_used_and_overridden() -> None:
  report = Report('T').add_text('t', 'x').set_render(options={'toc': False, 'accent': None})
  html = render_bundle(report.build(), formats=['html'], flat=True).files['report.html'].decode()
  assert 'class="toc"' not in html.split('</style>')[1]
  override = render_bundle(report.build(), formats=['html'], options={'toc': 'true'}, flat=True)
  assert override.manifest['options']['toc'] is True


def test_bad_options_are_an_aggregated_error() -> None:
  with pytest.raises(RenderError) as caught:
    render_bundle(kitchen_sink(), options={'toc': 'maybe', 'nope': 1})
  assert codes(caught.value.issues) == ['E806', 'E806']


def test_the_latex_engine_goes_into_latexmkrc() -> None:
  for engine, mode in (('pdflatex', 1), ('xelatex', 5), ('lualatex', 4)):
    files = render_bundle(kitchen_sink(), formats=['tex'], latex_engine=engine, flat=True).files
    assert f'$pdf_mode = {mode};' in files['latexmkrc'].decode()


@pytest.mark.parametrize(
  ('kwargs', 'fragment'),
  [({'markup_engine': 'pandoc'}, 'pandoc'), ({'math_renderer': 'katex'}, 'katex')],
)
def test_engines_that_do_not_exist_or_come_later_are_refused(
  kwargs: dict[str, str], fragment: str
) -> None:
  with pytest.raises(TemplateError) as caught:
    render_bundle(kitchen_sink(), **kwargs)  # type: ignore[arg-type]
  assert caught.value.code == 'E805' and fragment in caught.value.message


def test_warnings_become_errors_when_strict() -> None:
  report = Report('T').add_text('a', 'x').add_text('b', 'y').set_outline(['a'])
  assert codes(render_bundle(report.build(), formats=['md']).issues) == ['W401']
  with pytest.raises(RenderError) as caught:
    render_bundle(report.build(), formats=['md'], strict=True)
  assert caught.value.code == 'W401'


def test_nothing_is_written_when_an_error_is_found(tmp_path: Path) -> None:
  report = Report('T').add_table('t', {'a': [1]}).set_outline(['t', 'nope'])
  with pytest.raises(Exception):  # noqa: B017  (the outline is invalid at build time)
    render_bundle(report.build())
  assert list(tmp_path.iterdir()) == []


def test_write_puts_the_files_on_disk(tmp_path: Path) -> None:
  result = render_bundle(kitchen_sink(), formats=['md', 'tex'])
  written = result.write(tmp_path / 'out')
  assert (tmp_path / 'out' / 'md' / 'index.md').read_bytes() == result.files['md/index.md']
  assert (tmp_path / 'out' / 'tex' / 'figures' / 'figures.curve.pdf').is_file()
  assert len(written) == len(result.files)
  assert all(path.is_file() for path in written)


def test_a_template_syntax_error_has_a_file_and_line(tmp_path: Path) -> None:
  issues = render_issues(small(), 'ok\n{% if %}\n', 'md', tmp_path)
  assert codes(issues) == ['E704']
  assert issues[0].location == 'report.j2:2'


def small() -> Bundle:
  return Report('T').add_text('t', 'x').build()


def test_runtime_template_errors_are_coded(tmp_path: Path) -> None:
  cases = {
    '{{ nope }}': 'E803',
    "{{ ''.__class__ }}": 'E802',
    '{{ 1 / 0 }}': 'E804',
    '{{ data.t.nope }}': 'E803',
  }
  for body, code in cases.items():
    issues = render_issues(small(), body, 'md', tmp_path)
    errors = [i for i in issues if i.severity == 'error']
    assert codes(errors) == [code], body
    assert errors[0].location == 'report.j2:1'


def test_an_error_in_one_format_fails_the_whole_render(tmp_path: Path) -> None:
  template = write_template(tmp_path / 't', body='{{ c.text(data.t) }}')
  (template / 'report.tex.j2').write_text('((( nope )))', encoding='utf-8')
  with pytest.raises(RenderError) as caught:
    render_bundle(Report('T').add_text('t', 'x').build(), template=template, layout='minimal')
  assert codes(caught.value.issues) == ['E803']
  assert caught.value.issues[0].location == 'report.tex.j2:1'


def test_a_per_format_override_replaces_the_neutral_body(tmp_path: Path) -> None:
  template = write_template(tmp_path / 't', body='neutral {{ c.math("x") }}')
  (template / 'report.tex.j2').write_text(
    r'\textbf{(((meta.title)))} ((( c.math("y") )))', encoding='utf-8'
  )
  result = render_bundle(
    Report('T').add_text('t', 'x').build(), template=template, layout='minimal'
  )
  assert 'neutral' in result.files['md/report.md'].decode()
  assert r'\textbf{T} $y$' in result.files['tex/report.tex'].decode()


def test_a_template_for_other_specs_or_formats_is_refused(tmp_path: Path) -> None:
  old = write_template(tmp_path / 'a', body='x')
  (old / 'template.yaml').write_text(
    'spec: ">=2.0"\nname: old\nversion: 1\nformats: [md]\n', encoding='utf-8'
  )
  bundle = Report('T').add_text('t', 'x').build()
  with pytest.raises(RenderError) as caught:
    render_bundle(bundle, template=old, layout='minimal', formats=['html'])
  assert sorted(codes(caught.value.issues)) == ['E505', 'E706']
  assert 'supports data-file spec >=2.0' in caught.value.issues[0].message


def test_a_layout_missing_a_component_is_reported_before_rendering(tmp_path: Path) -> None:
  layout = write_layout(tmp_path / 'lay')
  components = layout / 'md' / 'components.md.j2'
  components.write_text(
    components.read_text(encoding='utf-8').replace('macro flow(', 'macro flux('), encoding='utf-8'
  )
  with pytest.raises(RenderError) as caught:
    render_bundle(Report('T').add_text('t', 'x').build(), layout=layout, formats=['md'])
  assert codes(caught.value.issues) == ['E707']
  assert "'flow'" in caught.value.issues[0].message


def test_a_layout_syntax_error_is_reported(tmp_path: Path) -> None:
  layout = write_layout(tmp_path / 'lay')
  (layout / 'html' / 'document.html.j2').write_text('{% if %}', encoding='utf-8')
  with pytest.raises(RenderError) as caught:
    render_bundle(Report('T').add_text('t', 'x').build(), layout=layout, formats=['html'])
  assert 'E704' in codes(caught.value.issues)
  assert caught.value.issues[0].location == 'html/document.html.j2:1'


def test_check_bundle_reports_what_only_a_render_shows(tmp_path: Path) -> None:
  report = (
    Report('T')
    .add_text('a', 'x')
    .add_text('b', 'y')
    .add_text('p', '# head\n\ntext', format='markdown')
  )
  report.set_outline(['a', 'p'])
  found = check_bundle(report.build(), formats=['html'])
  assert sorted(i.code for i in found.issues) == ['W401', 'W701']
  assert found.ok
  assert check_bundle(report.build(), formats=['html'], strict=True).exit_code == 2
  assert [i.code for i in check_bundle(report.build(), formats=['html'], render=False).issues] == []


def test_check_bundle_stops_at_static_errors() -> None:
  report = Report('T').add_text('a', 'x')
  report.set_render(layout='minimal@1')
  found = check_bundle(report.build(), template='generic@1', options={'bogus': 1})
  assert [i.code for i in found.issues] == ['E806'] and not found.ok


def test_dynamic_keys_are_warned_about_unless_the_template_declares_them(tmp_path: Path) -> None:
  body = "{% for k in keys('a') %}{{ c.value(v(k)) }}{% endfor %}"
  bundle = Report('T').add_text('a.x', 'x').build()
  assert 'W403' in report_of(bundle, body, 'md', tmp_path)
  template = write_template(tmp_path / 'declared', body=body, extra='dynamic_keys: true')
  found = check_bundle(bundle, template=template, layout='minimal', formats=['md'])
  assert found.issues == ()
