"""LaTeX fragments for manuscripts: macro names, numbers.tex, tables and figures."""

from __future__ import annotations

from pathlib import Path

import pytest
from hypothesis import given
from hypothesis import strategies as st
from render_fixtures import kitchen_sink

from scireport import ExportError, Report, export_tex, write_export
from scireport.export import macro_name
from scireport.export.tex import LONG_TABLE_ROWS, NUMBERS_FILE


@pytest.mark.parametrize(
  ('key', 'prefix', 'name'),
  [
    ('crossmatch.n_pairs', '', 'CrossmatchNPairs'),
    ('crossmatch.n_pairs', 'Ds', 'DsCrossmatchNPairs'),
    ('run2.count', '', 'RunTwoCount'),
    ('v10-x', '', 'VOneZeroX'),
    ('a', '', 'A'),
  ],
)
def test_macro_names(key: str, prefix: str, name: str) -> None:
  assert macro_name(key, prefix) == name


def test_a_prefix_must_be_letters() -> None:
  with pytest.raises(ValueError, match='letters only'):
    macro_name('a.b', 'x1')


@given(st.from_regex(r'[a-z0-9_-]+(\.[a-z0-9_-]+){0,3}', fullmatch=True))
def test_a_macro_name_is_always_letters(key: str) -> None:
  assert macro_name(key, 'P').isalpha()


def test_numbers_become_one_command_each() -> None:
  result = export_tex(kitchen_sink(), ['facts.n_pairs', 'facts.sep'])
  text = result.files[NUMBERS_FILE].decode()
  assert '\\newcommand{\\FactsNPairs}{3,061~pairs}' in text
  assert '\\newcommand{\\FactsSep}{1.23 \\ensuremath{\\pm} 0.04~arcsec}' in text
  assert result.macros == {'FactsNPairs': 'facts.n_pairs', 'FactsSep': 'facts.sep'}
  assert text.startswith('% Generated by scireport') and 'Do not edit.' in text.splitlines()[0]


def test_two_keys_with_one_macro_name_are_e807() -> None:
  report = Report('T').add_number('a.b_c', 1).add_number('a.b-c', 2)
  with pytest.raises(ExportError) as caught:
    export_tex(report.build())
  assert caught.value.code == 'E807' and 'ABC' in caught.value.message


def test_a_prefix_can_resolve_a_clash_with_a_command() -> None:
  report = Report('T').add_number('delta', 1)
  assert 'Delta' in export_tex(report.build()).macros
  assert 'XDelta' in export_tex(report.build(), prefix='X').macros


def test_a_table_is_a_float_with_caption_and_label() -> None:
  text = export_tex(kitchen_sink(), ['tables.cut']).files['tab_tables.cut.tex'].decode()
  assert '\\begin{table}[tbp]' in text and '\\caption{A table cut to five rows}' in text
  assert '\\label{tab:tables.cut}' in text and '% showing the first 5 of 40 rows' in text
  assert text.count(' \\\\') == 6  # header + five rows
  assert '\\toprule' in text and '\\bottomrule' in text


def test_table_cells_are_escaped_and_units_typeset() -> None:
  text = export_tex(kitchen_sink(), ['tables.inline']).files['tab_tables.inline.tex'].decode()
  assert 'c\\&d' in text and '50\\%' in text and 'a\\_b' in text
  assert 'Value (deg\\ensuremath{^{2}})' in text


def test_bare_tables_have_no_float_or_caption() -> None:
  text = export_tex(kitchen_sink(), ['tables.cut'], bare=True).files['tab_tables.cut.tex'].decode()
  assert '\\begin{table}' not in text and '\\caption' not in text and '\\label' not in text
  assert '\\begin{tabular}{rr}' in text


def test_max_rows_cuts_a_table() -> None:
  text = export_tex(kitchen_sink(), ['tables.cut'], max_rows=2).files['tab_tables.cut.tex'].decode()
  assert '% showing the first 2 of 40 rows' in text


def test_a_long_table_uses_longtable() -> None:
  report = Report('T').add_table(
    'big', {'n': list(range(LONG_TABLE_ROWS + 5))}, caption='Big', columns=[{'name': 'n'}]
  )
  text = export_tex(report.build()).files['tab_big.tex'].decode()
  assert '\\begin{longtable}{r}' in text and '\\endhead' in text and '\\label{tab:big}' in text
  assert '\\begin{table}' not in text


def test_a_figure_writes_its_fragment_and_the_pdf() -> None:
  result = export_tex(kitchen_sink(), ['figures.curve'], graphics_prefix='generated/')
  assert sorted(result.files) == ['fig_figures.curve.pdf', 'fig_figures.curve.tex']
  text = result.files['fig_figures.curve.tex'].decode()
  assert '\\includegraphics[width=0.6\\linewidth]{generated/fig_figures.curve.pdf}' in text
  assert '\\caption{y = x squared}' in text and '\\label{fig:figures.curve}' in text


def test_a_figure_without_pdf_or_png_is_e210() -> None:
  svg = b'<svg xmlns="http://www.w3.org/2000/svg"/>'
  report = Report('T').add_figure('f', {'svg': svg}, alt='a', formats=('svg',))
  with pytest.raises(ExportError) as caught:
    export_tex(report.build())
  assert caught.value.code == 'E210'


def test_patterns_select_several_keys() -> None:
  result = export_tex(kitchen_sink(), ['facts.*'])
  assert list(result.files) == [NUMBERS_FILE]
  assert len(result.macros) == 6


def test_everything_is_exported_when_no_key_is_given() -> None:
  names = set(export_tex(kitchen_sink()).files)
  assert (
    NUMBERS_FILE in names and 'tab_tables.csv.tex' in names and 'fig_figures.curve.tex' in names
  )
  assert not any(name.startswith('fig_figures.logo') for name in names)  # images have no fragment


def test_a_key_that_has_no_fragment_is_e808_when_named() -> None:
  with pytest.raises(ExportError) as caught:
    export_tex(kitchen_sink(), ['intro.plain'])
  assert caught.value.code == 'E808'


def test_an_unknown_key_is_e103_with_a_suggestion() -> None:
  with pytest.raises(ExportError) as caught:
    export_tex(kitchen_sink(), ['facts.n_pair', 'nope.*'])
  assert [i.code for i in caught.value.issues] == ['E103', 'E103']
  assert "Did you mean 'facts.n_pairs'?" in (caught.value.issues[0].hint or '')


def test_the_export_is_deterministic_and_written_to_disk(tmp_path: Path) -> None:
  first = export_tex(kitchen_sink(real=True))
  second = export_tex(kitchen_sink(real=True))
  assert first.files == second.files
  written = write_export(first, tmp_path / 'paper' / 'generated')
  assert [p.name for p in written] == list(first.files)
  assert (tmp_path / 'paper' / 'generated' / NUMBERS_FILE).read_bytes() == first.files[NUMBERS_FILE]
