"""LaTeX output: a project that compiles with plain ``latexmk`` outside scireport (ADR-0010).

The project holds ``report.tex``, the layout's style file, a ``latexmkrc`` that selects the TeX
engine, and ``figures/`` with PDF renditions preferred over PNG (SVG is never used).
"""

from __future__ import annotations

from pathlib import PurePosixPath
from typing import TYPE_CHECKING, Any

from scireport.render.outputs import tidy

if TYPE_CHECKING:
  from scireport.render.session import RenderSession

DOCUMENT = 'report.tex'
"""Name of the main file."""
LATEXMK_MODE = {'pdflatex': 1, 'xelatex': 5, 'lualatex': 4}
"""``$pdf_mode`` value that selects each engine in ``latexmkrc``."""


def variables(session: RenderSession) -> dict[str, Any]:
  """Return ``style``: the name (without suffix) of the layout's LaTeX style file, or ''."""
  style = session.layout.files('tex').style
  return {'style': PurePosixPath(style).stem if style else ''}


def split(session: RenderSession, body: str) -> tuple[str, dict[str, str]]:
  """Return the body unchanged: a LaTeX project has one main file."""
  del session
  return body, {}


def assemble(session: RenderSession, document: str, parts: dict[str, str]) -> dict[str, bytes]:
  """Return the project files: document, style, ``latexmkrc`` and the layout's assets."""
  del parts
  files = session.layout.files('tex')
  out = {
    DOCUMENT: tidy(document, 'tex'),
    'latexmkrc': (
      f'# Generated by scireport; run "latexmk {DOCUMENT}".\n'
      f'$pdf_mode = {LATEXMK_MODE[session.info.latex_engine]};\n'
    ).encode(),
  }
  if files.style:
    out[PurePosixPath(files.style).name] = session.layout.read(files.style).encode('utf-8')
  for name in files.assets:
    out[name] = (session.layout.root / name).read_bytes()
  return out
